name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  check:
    name: Build and test
    if: github.repository == 'apache/incubator-pekko-grpc-quickstart-scala.g8'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: sbt & Paradox
        run: sbt test docs/paradox

      - name: Maven
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test

      - name: Gradle
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build -i --no-daemon
